- name: Setup the default user and docker
  hosts: all
  roles:
    - docker
    - role: default_user
      default_user_username: "{{ global_default_user_name }}"
      default_user_password: "{{ global_default_user_password | string }}"
      default_user_pub_key: "{{ global_default_user_pub_key }}"
