- name: "Make sure that dnf-plugins-core is installed"
  remote_user: root
  ansible.builtin.dnf:
    name: dnf-plugins-core
    state: present

- name: "Make sure docker-ce repositories are added"
  command: dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo

- name: Make sure docker and all its dependencies is installed
  remote_user: root
  ansible.builtin.dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: latest
    allowerasing: true

- name: Make sure docker service is enabled and started
  remote_user: root
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
